### ISSUE TITLE
PC 后台 页面变形  测试服

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#115]
PC 后台 页面变形  测试服
在后台会员管理中的普通会员里，页面长度或上下间距扩大导致页面变形
![tl dk 3 y l r57 mf2 1n](https://cloud.githubusercontent.com/assets/21186754/18826219/e023aa00-83fe-11e6-8960-7c37109c8e7d.png)

**Comment by easonfan** [comment]
fixed by gaokaiaki

**Comment by yzc4410** [comment]
ok
