### ISSUE TITLE
PC 正式 绑卡界面问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#117]
PC 正式 绑卡界面问题
  在银行列表中跟换银行卡的弹出页面上下空白太多，小屏幕电脑拉不到底部，下面按钮看不到
  宝付跟换银行卡界面中没有身份证信息，富友跟换银行卡界面中没有借记卡信息
![vtoo 6u 1nvrko at qwsd](https://cloud.githubusercontent.com/assets/21186754/18938397/edf5232e-862a-11e6-86c5-8b22668f2f47.png)
![l t eg3c 85w x bu2xcn](https://cloud.githubusercontent.com/assets/21186754/18938399/efee786a-862a-11e6-937c-c872fff8b114.png)

**Comment by easonfan** [comment]
fixed and updated

**Comment by zjlhlihui123** [comment]
已解决
