### ISSUE TITLE
APP 安卓 IOS 动态页面字体太小

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#118]
APP 安卓 IOS 动态页面字体太小
在APP动态页面中的行业焦点和金融小知识两个模块里的文章字体太小，PC端正常大小,安卓个别手机页面前面有小框
![cf84b1ff24539c690ed191af65cc24be](https://cloud.githubusercontent.com/assets/21186754/18943316/565bf5ca-8651-11e6-860c-58c065119881.jpg)

**Comment by fujianlian** [comment]
小框问题是不同手机自身系统导致的，无法作出修改。
字体大小问题的与H5、后台一起协作解决
