### ISSUE TITLE
PC 正式服 换卡问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#130]
PC 正式服 换卡问题
用户换卡输入好信息以后点击提交成功
后台审核通过成功，但是前面没有变换更换后的银行卡信息，还是显示的原来的银行卡信息（昨天还好的）
![82usn6p1netyfq ej i rre](https://cloud.githubusercontent.com/assets/21186754/19340030/6de3de98-9159-11e6-9bf7-c6b027067931.png)
![8v4uusxdt_6 xcz4yb2ci 1](https://cloud.githubusercontent.com/assets/21186754/19340044/81a9b736-9159-11e6-947c-671bc3ccf388.png)
![cz rgysx 6u m 51h2kjy](https://cloud.githubusercontent.com/assets/21186754/19340033/732f4702-9159-11e6-8202-ed52ea367dcb.png)

**Comment by zjlhlihui123** [comment]
已解决
