### ISSUE TITLE
PC H5 正式服 充值问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#132]
PC H5 正式服 充值问题
PC 用户输入金额选择好富友点击充值按钮，点击前往网银支付（总）就直接跳转到了成功，并没有到网银界面
H5 输入金额“20000”点击确定没有任何反应
![d4xn ro y0 a m qsi3q](https://cloud.githubusercontent.com/assets/21186754/19342641/3abc24f6-9165-11e6-953a-f9cab57a8f3a.png)
![ttj8qdviwt7_r0p6 rdmn m](https://cloud.githubusercontent.com/assets/21186754/19342645/3dddf39e-9165-11e6-8afb-1e6325f0d83c.png)
![5us fpoa zcbs23wn_3imxk](https://cloud.githubusercontent.com/assets/21186754/19342649/417a7a36-9165-11e6-9e94-992c5b8d704a.png)

**Comment by zjlhlihui123** [comment]
已解决
