### ISSUE TITLE
PC 正式服 老用户实名问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#137]
PC 正式服 老用户实名问题
老用户“13818353682 赵剑英”之前用户验证过，已有过几次提现，今天10-17提现错误提示“请实名认证”

**Comment by zjlhlihui123** [comment]
一时间无法找出原因，边找边看边测试，看看是否还会出现这个问题。暂时只能先把实名认证改回来

**Comment by yzc4410** [comment]
ok
