### ISSUE TITLE
PC 正式服 流标金额问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#139]
PC 正式服 流标金额问题
用户之前投资的标“CSTS01”“CSTS01”“YCT20160128”3个标留标后金额没有返还到18149770407此账号里

![4b b lfu g bds w8xsn](https://cloud.githubusercontent.com/assets/21186754/19466766/ea324c20-953f-11e6-9637-51ff80486cd3.png)

**Comment by zjlhlihui123** [comment]
已解决，运营操作流程的失误
