### ISSUE TITLE
APP  PC后台 投标状态未变更，满标无法放款

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#22]
APP
安卓  IOS  
用户投资新手表 “个人投资测试标”金额2000  投标投满后
问题1：未放款，项目标的状态为还款中
问题2：后台标的状态还是筹款中，无法满标放款
问题3：后台 系统首页页面中，在满标的借款这一栏没有已满标的标数量

**Comment by xutin** [comment]
这个应该是后台问题， @yzrxxd

**Comment by zjlhlihui123** [comment]
无法修改，原始标已不存在，无法查找原因

**Comment by yzc4410** [comment]
OK
