### ISSUE TITLE
H5 邀请好友未收到 1000积分

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#27]
H5 邀请好友未收到 1000积分
老用户（邀请人）发链接邀请新用户
新用户注册成功，实名成功
老用户（邀请人）未收到1000积分，而且任务显示未完成

**Comment by txwm** [comment]
@wpf12138

**Comment by txwm** [comment]
H5原先注册没有加邀请人信息，存入数据库，原先没有这个功能，所以后面步骤实现不了

**Comment by txwm** [comment]
@wpf12138
