### ISSUE TITLE
紧急 PC 前台 投资 和 提现问题 正式服务器

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#30]
PC 前台 投资 和 提现问题
在PC端 投资金额已经全部投光后还能继续投资，显示为负数
在PC端 提现金额提到零为止后还能继续提现，显示为负数

**Comment by yzc4410** [comment]
![4sz1lu 3671lxw 7xyyn8 4](https://cloud.githubusercontent.com/assets/21186754/18198774/157b1404-7130-11e6-8050-69ae9d326c00.png)

**Comment by txwm** [comment]
解决，上传测试

**Comment by txwm** [comment]
解决，上传测试
