### ISSUE TITLE
PC 前台 支付成功跳转域名出错

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#32]
![h yyjdh4cp 33c d7tpdf](https://cloud.githubusercontent.com/assets/21186754/18236002/3d2605d8-7354-11e6-9934-b4fdbd3c29f9.png)
支付成功以后跳转到http://121.40.29.79/ 服务器上

**Comment by easonfan** [comment]
前端的锅已经解决 并git上传到fuyou的支付分支 后端的锅@李辉

**Comment by zjlhlihui123** [comment]
已解决
