### ISSUE TITLE
PC 测试服 后台 加息劵创建错误

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#40]
PC 测试服 后台 加息劵创建错误
用户在后台创建加息劵
→在加息率这里无论填写格式提示错误（（加息率不能超过3％ 输入格式如下：0.20）0.20格式错误）
→文本框中小数点后面长度教研未有
→文本框输入0.0299后点击确定四舍五入到0.03

**Comment by easonfan** [comment]
OK

**Comment by yzc4410** [comment]
OK
