### ISSUE TITLE
APP  安卓  投资超额度错误

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#59]
APP  安卓  投资超额度错误
→投资民爱宝（26测试标）剩余额度0.18万（1800）！系统显示已经超过额度！但是实际上就只剩1800没投！

**Comment by fujianlian** [comment]
后台数据问题，比如剩余1750没投，后台返回数据0.73万相当于7300，所以出现上述问题

**Comment by zjlhlihui123** [comment]
已解决

**Comment by yzc4410** [comment]
OK
