### ISSUE TITLE
PC 短信收不到 后台内容看不到

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#71]
PC 短信收不到 后台内容看不到
![l hct jf setq jz 1vyua](https://cloud.githubusercontent.com/assets/21186754/18372734/5a85fc80-7671-11e6-8358-166f6d39153e.png)

 在PC前台设置支付密码，获取短信收不到
 在后台“短信邮件”中的业务队列列表，看不到发送的短信内容，但发送时成功的，短信收不到

**Comment by lilianmin** [comment]
已解决！

**Comment by yzc4410** [comment]
ok
