### ISSUE TITLE
APP 数据后台 资产错误

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#73]
APP 数据后台 资产错误
![9db1ac113e844275ec16747fbf6448a0](https://cloud.githubusercontent.com/assets/21186754/18373580/ee6d3020-7677-11e6-982d-93e5eb1ec486.jpg)

用户投资一个项目标1000元，满标放款完成后总资产金额没减反而多1015.71了，已投里的金额也多了1016.71元,已投和总资产的金额误差1元

**Comment by yzrxxd** [comment]
已经修改

**Comment by yzc4410** [comment]
OK
