### ISSUE TITLE
PC 前台  注册验证码错误无法注册

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#77]
PC 前台  注册验证码错误
![jnt4 1rph qd v givx9r g](https://cloud.githubusercontent.com/assets/21186754/18379291/4d5c473e-76a4-11e6-8de6-6d340a16bbfb.png)

新用户注册验证码收不到，无法注册
在后台短信邮件中的业务队列列表里短信邮件发送失败，而且看不到内容

**Comment by txwm** [comment]
测试还是正式服，测试的话短信接口好像不能用了
