### ISSUE TITLE
H5 充值问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#88]
H5 充值问题
在充值时输入金额9999999元点击提交，显示无法完成支付，1003：字段不能为空：MCHNTCD
![0 8 _w 7f8 e5qv0wrtfl3](https://cloud.githubusercontent.com/assets/21186754/18427334/f15b9e14-78f9-11e6-9f93-428ac756173a.png)
充值2元成功后，没有记录
![x 7 _w9 ziac 9 fcrobt](https://cloud.githubusercontent.com/assets/21186754/18429081/1afc13b6-7904-11e6-8c13-490f3768b1ba.png)

**Comment by zjlhlihui123** [comment]
已解决

**Comment by yzc4410** [comment]
OK
