### ISSUE TITLE
H5 按钮重叠问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#90]
H5 按钮重叠问题
在投资项目页面中，关注和导航按钮重叠
![ted 9j7 6 t1 i19w ixomd](https://cloud.githubusercontent.com/assets/21186754/18430416/01453bee-790b-11e6-823d-df0e172a644b.png)

**Comment by txwm** [comment]
手机页面观看就可以了

**Comment by yzc4410** [comment]
OK
