### ISSUE TITLE
H5 短信验证码倒数问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#91]
H5 短信验证码倒数问题
用户在修改密码页面填写错误信息后点击短信验证码任然在倒数，只有填写正确信息才发送验证信息进行倒数
而且它一直在倒数，数字到1了以后变成重新获得验证码，但是它自动又从60秒又开始倒数
![sabdgn uut3q0ns 7ja rh](https://cloud.githubusercontent.com/assets/21186754/18430625/e81b3762-790b-11e6-9ced-dc90dc6cfa49.png)

**Comment by txwm** [comment]
解决，已上传
