### ISSUE TITLE
H5 完善资料问题

### ISSUE THREAD

**Issue by yzc4410** [minaidai1/minaidai#92]
![v x4 uaoubwzd7k 641z0](https://cloud.githubusercontent.com/assets/21186754/18431121/3119a780-790e-11e6-99fa-64ae2c5cdcfd.png)
H5 完善资料问题
用户已经绑定过银行卡，设置过支付密码，实名认证过，但这显示了都未成功

**Comment by txwm** [comment]
登录后测试

**Comment by txwm** [comment]
登录再后进行测试

**Comment by yzc4410** [comment]
OK
